server: "DESKTOP-3POIBU6"
port: "49734"
database: "softrestaurant10"
username: "sa"
password: "National09"
documento: "Grupo_Vierci.xlsx"
descuento:  "1" #id del descuento fijo para agregar. Si son sin descuento dejar vacío.